version: '2'

services:
    work:
        build:
            context: ./work
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        tty: true

    php-fpm:
        build:
            context: ./php-fpm
            dockerfile: Dockerfile-70
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG="serverName=laravel"
        links:
            - work

    ### Workspace Utilities Container ###########################
    nginx:
        build:
            context: ./nginx
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginx/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

    nginxhttp2:
        build:
            context: ./nginxhttp2
            args:
                - PHP_UPSTREAM=php-fpm
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/nginxhttp2/:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"
        links:
            - php-fpm

    ### MySQL Container #########################################

    mysql:
        build: ./mysql
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        build: ./phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret

        volumes_from:
            - volumes_data
        ports:
            - "8081:80"
        links:
            # for mysql container
            - "mysql:db"
            # for mariadb container

            # - "mariadb:db"
    # Elastic
    # 
    # 
    ### Redis Container #########################################

    redis:
        build: ./redis
        volumes_from:
            - volumes_data
        ports:
            - "6379:6379"


    elasticsearch:
        build: ./elasticsearch
        environment:
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"
        volumes_from:
            - volumes_data
        ports:
            - "9200:9200"
            - "9300:9300"

    ################################NODE JS ================================
    node:
        build: ./node

        volumes_from:
            - volumes_data
        links:
            # for mysql container
            - work
            # for mariadb container
            # - "mariadb:db"

    volumes_source:
        image: tianon/true
        volumes:
            - ../:/var/www/sites

    volumes_data:
        image: tianon/true
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/sessions:/sessions
            - ./data/elasticsearch/data:/usr/share/elasticsearch/data
            - ./data/redis:/data
