FROM ubuntu

MAINTAINER Nipe Setiawan Harefa <nipeharefa@gmail.com>

RUN apt update && apt install php php-cli php-mbstring php-xml curl vim -y
RUN curl -sL https://deb.nodesource.com/setup_4.x | bash -
RUN apt-get install -y nodejs